# SPDX-License-Identifier: MPL-2.0
# Funding platforms for metadatastician projects
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: metadatastician
ko_fi: metadatastician
liberapay: metadatastician
